export const SET_TASK_FROM_INPUT = "SET_TASK_FROM_INPUT";
export const SET_SCHEDULE = "SET_SCHEDULE";
export const ADD_TASK_TO_LIST = "ADD_TASK_TO_LIST";
export const UPDATE_CATEGORY_AMOUNT = "UPDATE_CATEGORY_AMOUNT";
